name: sedge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build sedge
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18.2'

    - name: Check Go fmt
      run: make gofmt

    - name: Check go mod status
      run: |
        make gomod_tidy
        if [[ ! -z $(git status -s) ]]
        then
          echo "Go mod - state is not clean:"
          git status -s
          git diff "$GITHUB_SHA"
          exit 1
        fi

    - name: Build
      run: make build
